[package]
name = "savana-kernel-protocol"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
minicbor.workspace = true
base64.workspace = true
sha2.workspace = true
hmac.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
x25519-dalek.workspace = true
unicode-normalization.workspace = true
zeroize.workspace = true
ed25519-dalek.workspace = true

[dev-dependencies]
getrandom.workspace = true
rustix.workspace = true
serde_json.workspace = true
