//! First-party, encrypted-owner managed objects. Display labels are never lookup
//! authority. IDs are generated by the owner, never recycled, and survive edits.
//! This is a private source/admin API, not a model tool or an arbitrary filesystem
//! adapter. External providers still need their own immutable-identity contracts.
use super::{ContinuationDispatchPolicyV04, ContinuationResourceFactV04, G4Error};
use ed25519_dalek::{Signature, VerifyingKey};
use savana_continuation_core::ledger::ResourceKey;
use savana_kernel_protocol::v2::{ActionContentV2, Digest32V2, UnixMillisV2};
use serde::{Deserialize, Serialize};

/// A closed source-to-business projection, never a general raw attachment.
#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ManagedInputProjectionV04 {
    Utf8PayloadV1,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ManagedSourcePolicyV04 {
    pub schema: u16,
    pub installation: [u8; 32],
    pub source: [u8; 32],
    pub namespace: [u8; 32],
    pub target: [u8; 32],
    pub resource_issuer: [u8; 32],
    pub not_before: u64,
    pub expires_at: u64,
    pub max_objects: usize,
    pub max_object_bytes: usize,
    pub max_mutations: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_projection: Option<ManagedInputProjectionV04>,
}
impl ManagedSourcePolicyV04 {
    fn validate(&self) -> Result<(), G4Error> {
        if self.schema != 1
            || self.not_before >= self.expires_at
            || [
                self.installation,
                self.source,
                self.namespace,
                self.target,
                self.resource_issuer,
            ]
            .contains(&[0; 32])
            || self.max_objects == 0
            || self.max_objects > 1024
            || self.max_object_bytes == 0
            || self.max_object_bytes > 32 * 1024
            || self.max_mutations == 0
            || self.max_mutations > 65_536
        {
            return Err(G4Error::StateConflict);
        }
        if VerifyingKey::from_bytes(&self.resource_issuer)
            .map_err(|_| G4Error::StateConflict)?
            .is_weak()
        {
            return Err(G4Error::StateConflict);
        }
        Ok(())
    }
    pub fn signing_digest(&self) -> Result<[u8; 32], G4Error> {
        self.validate()?;
        let bytes = serde_json::to_vec(self).map_err(|_| G4Error::StateConflict)?;
        Ok(
            *super::task_authorization::hash_parts(b"SAVANA_MANAGED_SOURCE_V04\0", &[&bytes])
                .as_bytes(),
        )
    }
    fn current(&self, now: UnixMillisV2) -> Result<(), G4Error> {
        if now.get() < self.not_before || now.get() >= self.expires_at {
            return Err(G4Error::StateConflict);
        }
        Ok(())
    }
}

#[derive(Clone)]
pub struct VerifiedManagedSourceV04 {
    policy: ManagedSourcePolicyV04,
}
impl VerifiedManagedSourceV04 {
    /// The caller selects expected installation and administrator key from trusted
    /// deployment state, not the proposal. No unsigned/Deserialize proof path.
    pub fn verify(
        bytes: &[u8],
        signature: &[u8; 64],
        admin: &VerifyingKey,
        installation: Digest32V2,
        now: UnixMillisV2,
    ) -> Result<Self, G4Error> {
        if bytes.len() > 4096 {
            return Err(G4Error::StateConflict);
        }
        let policy: ManagedSourcePolicyV04 =
            serde_json::from_slice(bytes).map_err(|_| G4Error::StateConflict)?;
        if serde_json::to_vec(&policy).map_err(|_| G4Error::StateConflict)? != bytes
            || policy.installation != *installation.as_bytes()
        {
            return Err(G4Error::StateConflict);
        }
        policy.current(now)?;
        admin
            .verify_strict(&policy.signing_digest()?, &Signature::from_bytes(signature))
            .map_err(|_| G4Error::StateConflict)?;
        Ok(Self { policy })
    }
    pub(super) fn scope(&self) -> ([u8; 32], [u8; 32]) {
        (self.policy.source, self.policy.namespace)
    }
}

/// Private source read. The host must authenticate the reader before calling.
/// Deliberately no Debug/Serialize: content and labels are not log/status fields.
pub struct ManagedResourceViewV04 {
    pub key: ResourceKey,
    pub revision: u64,
    pub deleted: bool,
    pub label: String,
    pub content: Vec<u8>,
}

/// Canonical immutable selector for this first-party provider only. The provider
/// must resolve this exact ID; display names/paths must never be re-resolved.
pub fn managed_resource_locator_v04(key: ResourceKey) -> Result<String, G4Error> {
    use std::fmt::Write;
    if key.incarnation != 0 || [key.source, key.namespace, key.object].contains(&[0; 32]) {
        return Err(G4Error::StateConflict);
    }
    let mut locator = String::from("savana-object-v1:");
    for (i, part) in [key.source, key.namespace, key.object].iter().enumerate() {
        if i != 0 {
            locator.push(':');
        }
        for byte in part {
            write!(&mut locator, "{byte:02x}").map_err(|_| G4Error::StateConflict)?;
        }
    }
    Ok(locator)
}
pub fn managed_resource_selector_digest_v04(
    target: Digest32V2,
    key: ResourceKey,
) -> Result<Digest32V2, G4Error> {
    if *target.as_bytes() == [0; 32] {
        return Err(G4Error::StateConflict);
    }
    Ok(super::task_authorization::hash_parts(
        b"SAVANA_BUSINESS_RESOURCE_V2_SCHEMA1\0",
        &[
            target.as_bytes(),
            managed_resource_locator_v04(key)?.as_bytes(),
        ],
    ))
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Object {
    id: [u8; 32],
    revision: u64,
    deleted: bool,
    label: String,
    content: Vec<u8>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    policy: ManagedSourcePolicyV04,
    mutations: u64,
    objects: Vec<Object>,
}
#[derive(Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ManagedSourcesV04 {
    sources: Vec<Source>,
}

fn valid_label(label: &str) -> bool {
    label.len() <= 256 && !label.chars().any(char::is_control)
}
impl ManagedSourcesV04 {
    /// Resolve only the signed task's source and exact immutable selector.
    /// Labels, paths and caller-supplied source identities are never authority.
    pub(super) fn admission_key(
        &self,
        policy: &ContinuationDispatchPolicyV04,
        payload: &savana_kernel_protocol::v2::TaskExecutionPayloadV2,
        now: UnixMillisV2,
    ) -> Result<ResourceKey, G4Error> {
        let source = self.source(policy.source, policy.namespace)?;
        source.policy.current(now)?;
        if source.policy.execution_projection != Some(ManagedInputProjectionV04::Utf8PayloadV1)
            || source.policy.resource_issuer != policy.resource_issuer
            || payload.request().profile().target_identity().as_bytes() != &source.policy.target
        {
            return Err(G4Error::StateConflict);
        }
        for object in &source.objects {
            let key = ResourceKey {
                source: policy.source,
                namespace: policy.namespace,
                object: object.id,
                incarnation: 0,
            };
            if managed_resource_locator_v04(key)? == payload.request().resource() {
                if object.deleted || object.content != payload.request().payload().as_bytes() {
                    return Err(G4Error::StateConflict);
                }
                return Ok(key);
            }
        }
        Err(G4Error::StateConflict)
    }

    pub(super) fn has_handoff_policy(&self) -> bool {
        self.sources
            .iter()
            .any(|s| s.policy.execution_projection.is_some())
    }
    pub(super) fn check_execution_handoff(
        &self,
        snapshot: &super::managed_execution::StoredManagedExecutionSnapshotV04,
        payload: &savana_kernel_protocol::v2::TaskExecutionPayloadV2,
        now: UnixMillisV2,
    ) -> Result<(), G4Error> {
        let b = &snapshot.body;
        let source = self.source(b.resource.source, b.resource.namespace)?;
        source.policy.current(now)?;
        if source.policy.execution_projection != Some(ManagedInputProjectionV04::Utf8PayloadV1)
            || source.policy.signing_digest()? != b.source_policy
            || payload.request().profile().target_identity().as_bytes() != &source.policy.target
            || payload.request().resource() != managed_resource_locator_v04(b.resource)?
            || payload.request().payload().as_bytes() != b.content
        {
            return Err(G4Error::StateConflict);
        }
        // Payload is already a validated UTF-8 field. No binary/text conversion,
        // label append, path resolution, template evaluation, or current reread.
        Ok(())
    }
    pub(super) fn freeze_execution(
        &self,
        policy: &ContinuationDispatchPolicyV04,
        reservation: &savana_continuation_core::ledger::Reservation,
        fact: &ContinuationResourceFactV04,
    ) -> Result<Option<super::managed_execution::StoredManagedExecutionSnapshotV04>, G4Error> {
        let Some(revision) = fact.managed_revision else {
            return Ok(None);
        };
        let s = self.source(policy.source, policy.namespace)?;
        let view = self.view(reservation.resource)?;
        if view.deleted || view.revision != revision {
            return Err(G4Error::StateConflict);
        }
        let snapshot = super::managed_execution::StoredManagedExecutionSnapshotV04::new(
            super::managed_execution::SnapshotBody {
                schema: 1,
                execution: reservation.execution,
                request_binding: reservation.request_binding,
                dispatch_policy: policy.signing_digest()?,
                source_policy: s.policy.signing_digest()?,
                action_content: fact.action_content,
                resource: view.key,
                revision,
                label: view.label,
                content: view.content,
            },
        )?;
        self.validate_execution_snapshot(policy, reservation, fact, &snapshot)?;
        Ok(Some(snapshot))
    }

    pub(super) fn validate_execution_snapshot(
        &self,
        policy: &ContinuationDispatchPolicyV04,
        reservation: &savana_continuation_core::ledger::Reservation,
        fact: &ContinuationResourceFactV04,
        snapshot: &super::managed_execution::StoredManagedExecutionSnapshotV04,
    ) -> Result<(), G4Error> {
        snapshot.validate_binding(policy, reservation, fact)?;
        let s = self.source(policy.source, policy.namespace)?;
        let b = &snapshot.body;
        let current = self.view(b.resource)?;
        if b.source_policy != s.policy.signing_digest()?
            || b.content.len() > s.policy.max_object_bytes
            || current.revision < b.revision
            || (current.revision == b.revision
                && (current.deleted || current.content != b.content || current.label != b.label))
        {
            return Err(G4Error::StateConflict);
        }
        Ok(())
    }

    pub(super) fn is_empty(&self) -> bool {
        self.sources.is_empty()
    }
    pub(super) fn install(
        &mut self,
        verified: VerifiedManagedSourceV04,
        installation: Digest32V2,
        now: UnixMillisV2,
    ) -> Result<bool, G4Error> {
        let p = verified.policy;
        if p.installation != *installation.as_bytes() {
            return Err(G4Error::StateConflict);
        }
        p.current(now)?;
        if let Some(s) = self
            .sources
            .iter()
            .find(|s| s.policy.source == p.source && s.policy.namespace == p.namespace)
        {
            return if s.policy == p {
                Ok(false)
            } else {
                Err(G4Error::StateConflict)
            };
        }
        if self.sources.len() >= 8 {
            return Err(G4Error::StateConflict);
        }
        self.sources.push(Source {
            policy: p,
            mutations: 0,
            objects: vec![],
        });
        Ok(true)
    }
    fn source(&self, source: [u8; 32], namespace: [u8; 32]) -> Result<&Source, G4Error> {
        self.sources
            .iter()
            .find(|s| s.policy.source == source && s.policy.namespace == namespace)
            .ok_or(G4Error::StateConflict)
    }
    pub(super) fn has_source(&self, source: [u8; 32], namespace: [u8; 32]) -> bool {
        self.source(source, namespace).is_ok()
    }
    /// Journal integrity needs only retained identity/revision, not private bytes.
    pub(super) fn retained_revision(&self, key: ResourceKey) -> Result<u64, G4Error> {
        if key.incarnation != 0 {
            return Err(G4Error::StateConflict);
        }
        self.source(key.source, key.namespace)?
            .objects
            .iter()
            .find(|object| object.id == key.object)
            .map(|object| object.revision)
            .ok_or(G4Error::StateConflict)
    }
    fn source_mut(
        &mut self,
        source: [u8; 32],
        namespace: [u8; 32],
    ) -> Result<&mut Source, G4Error> {
        self.sources
            .iter_mut()
            .find(|s| s.policy.source == source && s.policy.namespace == namespace)
            .ok_or(G4Error::StateConflict)
    }
    pub(super) fn create(
        &mut self,
        source: [u8; 32],
        namespace: [u8; 32],
        label: &str,
        content: &[u8],
        now: UnixMillisV2,
    ) -> Result<ResourceKey, G4Error> {
        let s = self.source_mut(source, namespace)?;
        s.policy.current(now)?;
        if !valid_label(label)
            || content.len() > s.policy.max_object_bytes
            || s.objects.len() >= s.policy.max_objects
            || s.mutations >= s.policy.max_mutations
        {
            return Err(G4Error::StateConflict);
        }
        // IDs never derive from payload, path, display label, revision or a model.
        for _ in 0..8 {
            let mut id = [0; 32];
            getrandom::getrandom(&mut id).map_err(|_| G4Error::DurableStateIo)?;
            if id == [0; 32] || s.objects.iter().any(|o| o.id == id) {
                continue;
            }
            s.objects.push(Object {
                id,
                revision: 1,
                deleted: false,
                label: label.into(),
                content: content.to_vec(),
            });
            s.mutations += 1;
            return Ok(ResourceKey {
                source,
                namespace,
                object: id,
                incarnation: 0,
            });
        }
        Err(G4Error::StateConflict)
    }
    pub(super) fn update(
        &mut self,
        key: ResourceKey,
        expected: u64,
        value: Option<(&str, &[u8])>,
        now: UnixMillisV2,
    ) -> Result<bool, G4Error> {
        if key.incarnation != 0 {
            return Err(G4Error::StateConflict);
        }
        let s = self.source_mut(key.source, key.namespace)?;
        s.policy.current(now)?;
        if value.is_some_and(|(label, content)| {
            !valid_label(label) || content.len() > s.policy.max_object_bytes
        }) {
            return Err(G4Error::StateConflict);
        }
        let o = s
            .objects
            .iter_mut()
            .find(|o| o.id == key.object)
            .ok_or(G4Error::StateConflict)?;
        if o.revision != expected {
            return Err(G4Error::StateConflict);
        }
        if o.deleted {
            return if value.is_none() {
                Ok(false)
            } else {
                Err(G4Error::StateConflict)
            };
        }
        if value.is_some_and(|(label, content)| o.label == label && o.content == content) {
            return Ok(false);
        }
        if s.mutations >= s.policy.max_mutations {
            return Err(G4Error::StateConflict);
        }
        o.revision = o.revision.checked_add(1).ok_or(G4Error::StateConflict)?;
        match value {
            Some((label, content)) => {
                o.label = label.into();
                o.content = content.to_vec();
            }
            None => {
                o.deleted = true;
                o.label.clear();
                o.content.clear();
            }
        }
        s.mutations += 1;
        Ok(true)
    }
    pub(super) fn view(&self, key: ResourceKey) -> Result<ManagedResourceViewV04, G4Error> {
        if key.incarnation != 0 {
            return Err(G4Error::StateConflict);
        }
        let s = self.source(key.source, key.namespace)?;
        let o = s
            .objects
            .iter()
            .find(|o| o.id == key.object)
            .ok_or(G4Error::StateConflict)?;
        Ok(ManagedResourceViewV04 {
            key,
            revision: o.revision,
            deleted: o.deleted,
            label: o.label.clone(),
            content: o.content.clone(),
        })
    }
    pub(super) fn policy_matches(
        &self,
        p: &ContinuationDispatchPolicyV04,
        installation: [u8; 32],
    ) -> Result<(), G4Error> {
        if let Ok(s) = self.source(p.source, p.namespace) {
            if s.policy.resource_issuer != p.resource_issuer
                || s.policy.installation != installation
            {
                return Err(G4Error::StateConflict);
            }
        }
        Ok(())
    }

    pub(super) fn require_registered_policy(
        &self,
        policy: &ContinuationDispatchPolicyV04,
        installation: [u8; 32],
    ) -> Result<(), G4Error> {
        self.source(policy.source, policy.namespace)?;
        self.policy_matches(policy, installation)
    }
    pub(super) fn check_fact(
        &self,
        p: &ContinuationDispatchPolicyV04,
        fact: &ContinuationResourceFactV04,
        action: &ActionContentV2,
        now: UnixMillisV2,
        historical: bool,
    ) -> Result<(), G4Error> {
        let s = match self.source(p.source, p.namespace) {
            Ok(s) => s,
            Err(_) => {
                return if fact.managed_revision.is_none() {
                    Ok(())
                } else {
                    Err(G4Error::StateConflict)
                }
            }
        };
        s.policy.current(now)?;
        let key = fact.resource;
        if key.source != p.source
            || key.namespace != p.namespace
            || key.incarnation != 0
            || p.resource_issuer != s.policy.resource_issuer
            || managed_resource_selector_digest_v04(Digest32V2::new(s.policy.target), key)?
                != action.action().resource_digest()
        {
            return Err(G4Error::StateConflict);
        }
        let o = s
            .objects
            .iter()
            .find(|o| o.id == key.object)
            .ok_or(G4Error::StateConflict)?;
        let revision = fact.managed_revision.ok_or(G4Error::StateConflict)?;
        if revision == 0
            || if historical {
                revision > o.revision || (o.deleted && revision == o.revision)
            } else {
                o.deleted || revision != o.revision
            }
        {
            return Err(G4Error::StateConflict);
        }
        Ok(())
    }
    pub(super) fn prepare_fact(
        &self,
        p: &ContinuationDispatchPolicyV04,
        action: &ActionContentV2,
        key: ResourceKey,
        now: UnixMillisV2,
    ) -> Result<ContinuationResourceFactV04, G4Error> {
        let s = self.source(p.source, p.namespace)?;
        let view = self.view(key)?;
        let expires_at = now
            .get()
            .checked_add(p.max_evidence_age_ms)
            .ok_or(G4Error::StateConflict)?
            .min(p.expires_at)
            .min(s.policy.expires_at);
        let fact = ContinuationResourceFactV04 {
            schema: 1,
            policy: p.signing_digest()?,
            action_content: *savana_kernel_protocol::v2::action_content_digest_v2(action)
                .map_err(|_| G4Error::StateConflict)?
                .as_bytes(),
            resource: key,
            issued_at: now.get(),
            expires_at,
            managed_revision: Some(view.revision),
        };
        fact.signing_digest()?;
        self.check_fact(p, &fact, action, now, false)?;
        Ok(fact)
    }
    pub(super) fn validate(&self) -> Result<(), G4Error> {
        if self.sources.len() > 8 {
            return Err(G4Error::DurableStateCorrupt);
        }
        for (i, s) in self.sources.iter().enumerate() {
            s.policy
                .validate()
                .map_err(|_| G4Error::DurableStateCorrupt)?;
            if s.objects.len() > s.policy.max_objects
                || s.mutations > s.policy.max_mutations
                || self.sources[..i].iter().any(|a| {
                    a.policy.source == s.policy.source && a.policy.namespace == s.policy.namespace
                })
            {
                return Err(G4Error::DurableStateCorrupt);
            }
            let mut total_revisions = 0u64;
            for (j, o) in s.objects.iter().enumerate() {
                if o.id == [0; 32]
                    || o.revision == 0
                    || s.objects[..j].iter().any(|a| a.id == o.id)
                    || !valid_label(&o.label)
                    || o.content.len() > s.policy.max_object_bytes
                    || (o.deleted
                        && (o.revision < 2 || !o.content.is_empty() || !o.label.is_empty()))
                {
                    return Err(G4Error::DurableStateCorrupt);
                }
                total_revisions = total_revisions
                    .checked_add(o.revision)
                    .ok_or(G4Error::DurableStateCorrupt)?;
            }
            if total_revisions != s.mutations {
                return Err(G4Error::DurableStateCorrupt);
            }
        }
        Ok(())
    }
}
