[package]
name = "savana-private-workflow"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
savana-kernel-protocol = { path = "../savana-kernel-protocol" }
savana-policy-core = { path = "../savana-policy-core" }
serde.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
hmac.workspace = true
aes-gcm.workspace = true
getrandom.workspace = true
zeroize.workspace = true
nix.workspace = true
thiserror.workspace = true
